# Generated by Django 3.1.2 on 2020-12-01 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
